/* Wrapper to expose mavlink20 for modules that expect it.
   The heavy autogenerated mavlink implementation lives under src/assets/mavlink.js
*/
/* eslint-disable import/extensions, import/no-unresolved */

import mavlink from '../assets/mavlink.js'

export const mavlink20 = mavlink

export default mavlink
