name: Node CI

on: [push, pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install selenium-standalone@latest -g
            - run: selenium-standalone install
            - run: selenium-standalone start &
            - run: npm install
            - run: npm run build --if-present
            - run: wget http://dl.google.com/linux/deb/pool/main/g/google-chrome-unstable/google-chrome-unstable_72.0.3595.2-1_amd64.deb
            - run: sudo apt install -y ./google-chrome-unstable_72.0.3595.2-1_amd64.deb
            - run: sudo apt install -y default-jdk
            - run: npm run e2e
            - run: npm run unit
              env:
                  CI: true

    testwindows:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
            - name: Use Node.js ${{ matrix.node-version }} in Windows
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm run build --if-present
            - run: npm run unit
